title: Computer Vision Lab
email: nikolasent@gmail.com
author: Nikolay Falaleev
language: en
logo: /static/img/avatar.png
about: by Nikolay Falaleev
description: > 
  A Robotics, Computer Vision and Machine Learning lab by Nikolay Falaleev. The main focus of the blog is the application of Deep Learning for Computer Vision tasks, as well as other relevant topics: classical Computer Vision, Numerical Methods, and Hardware.
baseurl: ""
url: "https://nikolasent.github.io"  # the base hostname & protocol
github:  NikolasEnt

allowsearch: false
enableTags:  true

paginate: 10
per_page: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
  math_engine: mathjax

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

social:
  name: Nikolay Falaleev
  links:
    - https://www.linkedin.com/in/nikolay-falaleev
    - https://github.com/nikolasent

webmaster_verifications:
  google: Br0cGLeUZYAHZBBiUTzR9Nd9CUQx3bW9ol6328RM-38